# docker-compose.yml
version: '3'
services:
  api:
    container_name: scholar_ingest_API
    build: .
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - .:/app

  database:
    container_name: scholar_ingest_DB
    image: "postgres"
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
     - ./data/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql